### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ChrisMBarr** [adrianrodriguez/push_it#1]
It might be a good idea to use actual `<button>` or `<a>` tags instead of a `<div>` - this way they can actually be used without having to hook up any javascript. They would also degrade nicely for older browsers.

Not totally sure, but it might be possible to use the `:before` and `:after` pseudo-classes instead of having extra markup for the buttons.

So with those two suggestions combined, Ideally it would be nice to just have `<button type='submit'>Click Me</button>` and it just works.

Also, some CSS animations might be cool for the hover and click states.

**Comment by adrianrodriguez** [comment]
Thanks Chris, those are some good suggestions. I think I will set a milestone for those, so stay tuned.

**Comment by EricR** [comment]
Great work.

I would also append:

```
/* line 102, ../sass/button.sass */
.button, .button_underneath {
   font-weight: bold;
   font-family: "Lobster", cursive;
   font-size: 15px;

   /* Make no selections */
   -moz-user-select: -moz-none;
   -khtml-user-select: none;
   -webkit-user-select: none;
  user-select: none;
}
```

So text doesn't get mistakingly selected when a button is pushed.

I also found when this was appended:

```
/* line 31, ../sass/button.sass */
.button:active {
    top: 1px;
}
```

It gave it a much more satisfying push! ;)

**Comment by adrianrodriguez** [comment]
Thanks for that Eric. I was wondering how to get rid of the accidental highlight from pushing. Also, forgot to add the homepage to the repo as well, I created a github page after creating this repo (still learning) http://adrianrodriguez.github.com
